Fix tile duplication
sharkwouter/minigalaxy pull request #201
Opened 2020-11-18 00:23 UTC by makson96

For some reason it seems that game name in gameinfo file can be different that the one obtained from API. As a result minigalaxy identifies those titles as separate games:
![stellaris_duplication](https://user-images.githubusercontent.com/1833284/99466039-ef53fc00-293b-11eb-89a8-6fec5f733978.png)
Identifying games by ID seems to be more reliable idea. In this pull request I want to address this issue by changing game recognition (for tile creating) from game titles to game ids.
I know this is very regression prone part of the code, so I am also introducing unit tests for it to make sure that any future modifications won't break it.

2020-11-18 08:25 UTC, sharkwouter commented
Yeah, I have observed this as well, good catch. Does this code also work for games which do not have an id on disk?

2020-11-18 21:24 UTC, makson96 commented
Well... it does not. I will try to prepare valid unit test for such a situation tomorrow and address it in the code.

2020-11-19 11:50 UTC, makson96 commented
The issue you mentioned is now addressed and I have also added unit test for checking such a situations.

2020-11-19 21:00 UTC, sharkwouter requested changes
This looks pretty good, but there is one thing I noticed which was a bit strange. I made a comment on that. Thanks for the work on this.

2020-11-19 21:08 UTC, makson96 commented on minigalaxy/ui/library.py
> +def add_games_from_api(self_games, self_api):
Well, I am unable to initialize this class for the sake of unit tests...

2020-11-21 12:05 UTC, merged