Add disk space checking before download part2.
sharkwouter/minigalaxy pull request #291
Opened 2021-02-14 22:52 UTC by makson96

Hi,
This is continuation of this pull request:
https://github.com/sharkwouter/minigalaxy/pull/147
Original author stated on Discord, that he won't have time to finish it and it is ok for someone else to do it.

I am pushing it here with some changes as pull request. It looks like this now:
![disk_space_check](https://user-images.githubusercontent.com/1833284/107891469-2af06900-6f1f-11eb-98df-8839223d1bbd.png)

Please do not merge it yet as I want to:
- Write some unit tests
- Add config option to ignore disk space check (it is based on approximation, so in some cases it might be very bad and user might want to disable it)
- Tune magic_ratio

Before I continue I would like to hear your comments about it.
Best regards,

2021-02-15 09:00 UTC, sharkwouter reviewed
This seems like a pretty good solution, although it does have a disadvantage. When the download actually starts, the disk space available can have changed. I'm not sure if this PR addresses that well. The code does look clean in general.

An alternative method to do this would probably be to also check when the download actually starts. Not sure. The download manager does know the size of a file it downloads when it start downloading something, but it doesn't know the Window so it cannot correctly show an error message at the moment. Something to think about, I'm not sure what the best solution is at the moment.

2021-02-15 09:10 UTC, makson96 commented on minigalaxy/ui/gametile.py
> +                          _("Not enough disk space to install game."))
Well, I am doing here also approximation of installed game size (based on installer size), so as a result we actually check if we have space for whole install process to take place.

2021-02-15 09:11 UTC, makson96 commented on minigalaxy/installer.py
> +    reserved_space = 0
What do you thing about 500MB as a safe reserve?

2021-02-15 10:54 UTC, sharkwouter commented
I've converted this to a draft, since you're saying not to merge this yet.

2021-03-28 14:04 UTC, makson96 commented
Sorry for long wait. Code is now ready for merge. Please check it.

2021-04-02 15:50 UTC, makson96 commented
To test it manipulated "reserved_space" in check_diskspace().
After receiving error (during game installation), change "Ignore disk space" in preferences and retry to install game.

2021-04-13 15:42 UTC, makson96 commented
OK. Changes requested on Discored are implemented. Please review.

2021-04-13 15:58 UTC, sharkwouter requested changes
Thanks for addressing it! The code looks really good, I just had a couple of small nitpicks.

2021-04-13 15:58 UTC, sharkwouter commented on minigalaxy/installer.py
> +    reserved_space = 500*1024*1024
I'd leave out reserved space. We can't really determine that and not all partitions have it, only the root partition.

2021-04-13 15:58 UTC, sharkwouter commented on minigalaxy/ui/gametile.py
> +        ds_ok = check_diskspace(total_file_size, Config.get("install_dir"))
This doesn't really need a variable I think. It's only used once in the line below.

2021-04-13 15:58 UTC, sharkwouter commented on minigalaxy/installer.py
> +def get_availablediskspace(location):
Could you change this to get_available_disk_space?

2021-04-13 15:58 UTC, sharkwouter commented on minigalaxy/installer.py
> +    magic_ratio = 1.5
I don't think we'll need the magic ratio in the future. Not sure if we should keep it for now or not.

2021-04-21 11:28 UTC, makson96 commented
Please review. You can change line:
return size_value
in get_game_size_from_unzip()
to:
return size_value * 1000000000000
to generate new error.

2021-04-21 13:00 UTC, sharkwouter requested changes
This is really good now, awesome job. I've done some testing and it works really well. The method you use to check the disk space is very cool actually. I just found one minor nitpick, then it can be merged.

2021-04-21 15:58 UTC, makson96 commented
Done. Please review.

2021-04-21 16:10 UTC, merged

2021-04-21 16:11 UTC, sharkwouter commented
Thanks! I've merged it.