Add option to hide games in library
sharkwouter/minigalaxy pull request #309
Opened 2021-04-11 13:58 UTC by TotalCaesar659

I'm tired to wait this option and tried to make it by myself. @makson96 please check this.
Fixes https://github.com/sharkwouter/minigalaxy/issues/273.

2021-04-12 07:01 UTC, makson96 commented
I had slightly different idea about implementation, but such an approach seems to be fine too (I was thinking about button in hamburger menu to unhide all game).

There are some issues in the implementation (I will mark it in the code):
- games are hidden/unhidden from user only after Minigalaxy restart (or new show_hidden_games option change in Preferences). Games should be hidden after clicking proper option in game Properties and then OK instead.
- In library.py please do not change "__create_gametiles()". Please put proper implementation in "__filter_library_func()" and use "filter_library()" whenever you want to hide or unhide game.
- It would be desired to be also able to hide not installed games. Proper config support is now in place for this, but it is blocked in your code.

Thanks for your work.

2021-04-12 07:12 UTC, makson96 requested changes

2021-04-12 07:12 UTC, makson96 commented on minigalaxy/ui/library.py
> +                        self.__add_gametile(game)
Please put proper implementation in __filter_library_func() instead of __create_gametiles()

2021-04-12 07:12 UTC, makson96 commented on minigalaxy/ui/preferences.py
> +            self.parent.reset_library()
Once implementation is done in __filter_library_func() we will not need this "if" condition and reset_library(). Just filter_library() instead.

2021-04-12 07:12 UTC, makson96 commented on minigalaxy/ui/properties.py
> +            self.switch_properties_hide_game.set_sensitive(False)
We don't need it. It should be possible to hide not installed games now.

2021-04-12 07:12 UTC, makson96 commented on minigalaxy/ui/properties.py
> +            self.game.set_info("hide_game", self.switch_properties_hide_game.get_active())
This doesn't need to be under "if" condition (should work for not installed games too).

Once implementation is done in __filter_library_func() use filter_library() here.

2021-04-13 14:36 UTC, TotalCaesar659 commented
> I was thinking about button in hamburger menu to unhide all game.

It's better to move it to options window, cause there are less chance that somebody behind your back will see it. The window behind two mouseclicks is more safer than hamburger menu behind one I guess.

I tried to move the condition to __filter_library_func(), but it shows me "TypeError: __filter_library_func() missing 1 required positional argument: 'game'".

2021-04-13 15:22 UTC, makson96 commented
Instead of using "game" try "tile.game" here.
For example:
tile.game.get_info("hide_game")

2021-04-13 16:10 UTC, TotalCaesar659 commented
The condition works now, but saving shows "TypeError: filter_library() missing 1 required positional argument: 'switch'".

2021-04-13 16:57 UTC, makson96 commented
Hmm. Could you check if calling:
self.parent.library.filter_library()
instead of:
self.parent.filter_library()
solves this issue?

2021-04-13 18:05 UTC, TotalCaesar659 commented
The warning is gone, but library isn't updated and setting isn't saved.

2021-04-14 06:02 UTC, makson96 commented
You should add:
Config.set("show_hidden_games", self.switch_show_hidden_games.get_active())
in:
def save_pressed() (preferences.py)
If you have further issues, please remember to update your branch.

2021-04-14 13:07 UTC, TotalCaesar659 commented
I should have guessed. In properties.py (https://github.com/sharkwouter/minigalaxy/pull/309/files#diff-ad7117370a7d1ef849b4e36d90fd4bbade6985c915a37846ab3f0b7fc61eb4f5R64):
- self.parent.filter_library() shows "'GameTile' object has no attribute 'filter_library'";
- self.parent.library.filter_library() shows 'GameTile' object has no attribute 'library'.

2021-04-14 15:44 UTC, makson96 commented
I think that "Window" i parent of "Game Tile". Which makes it grandparent of "Properies" ;)
Try:
self.parent.parent.library.filter_library()

2021-04-14 15:52 UTC, TotalCaesar659 commented
`self.parent.parent.library.filter_library()` shows "'Library' object has no attribute 'library'", but `self.parent.parent.filter_library()` works. Looks like it's ready for review.

2021-04-14 18:01 UTC, makson96 approved these changes
I have tested it and it works as expected. Code also looks good for me.
@sharkwouter can you take a look?

2021-04-14 18:23 UTC, merged

2021-04-14 18:23 UTC, sharkwouter commented
Looks really good now, thanks!