DLC Download Queuing
sharkwouter/minigalaxy pull request #395
Opened 2021-10-29 23:10 UTC by flagrama

Made changes allowing DLC downloads to be queued up.

Should not delete the entire installer directory if other files exist in the directory. This would cause a race condition `remove_installer` in `installer.py` and `prepare_location` in `download_manager.py` so `prepare_location` will now create a placeholder file so that the directory will be much less likely be deleted between preparation and download starting.

The Menu button will not be hidden anymore, instead the Uninstall and Update buttons will be hidden while in a DOWNLOADING state, leaving Properties and DLC still accessible. Cancel button has been made to appear to the left of the Menu button now that they will appear together and would have overlapped previously.

`set_progress` in `gametile.py` has been modified to ensure downloads will update the tile's state back to DOWNLOADING with a progress bar after being left in INSTALLED after installing the previous download.

DLC Download buttons will be disabled after clicking on them.

Current Known Issues:
- Canceling a download will say it is cancelling the download of the game, not the DLC, this is the same as current behaviour, but is more confusing now due to the queuing.
- The change in `prepare_locations` may have introduced an issue where downloads may end up corrupt after downloading, though this could also easily be because of closing the application by killing the debugger.
- DLC Download button will not remain disabled. After a call to `__check_for_update_dlc` the buttons will be returned to their states dictated by `update_gtk_box_for_dlc`
- I have no idea what I'm doing with Glade. Hopefully I didn't break anything.

2021-10-29 23:15 UTC, flagrama commented
Will work on any issues the unit tests run into if other aspects of the PR seem fine.

2021-11-05 04:36 UTC, flagrama commented
This should be good for review, the tests should pass if the `os.remove` is mocked instead of `shutil.rmtree`. Though if cleaning up the download directory is still preferred I'll need to find a away to do it that doesn't suffer from the race condition.

2021-11-05 14:57 UTC, sharkwouter requested changes
I found one small issue with the code by looking at the test, besides that the code looks okay. I will try to find time to test this a bit later. Thanks for the work!

2021-11-05 14:57 UTC, sharkwouter commented on minigalaxy/download_manager.py
> +from os.path import exists
This import is not used and it making the linting test fail.

2021-11-09 14:19 UTC, flagrama commented
Okay, I'll take a look at it soon and try to fix that.

2021-11-12 21:50 UTC, flagrama commented
Ah, you must have deleted it with DLC already installed and redownloaded it. I'll look into how to fix that.

2021-11-12 22:03 UTC, flagrama commented
This is why I hate resolving merge conflicts with GitHub.

2021-11-12 22:12 UTC, flagrama commented
Not sure why the test failed
![image](https://user-images.githubusercontent.com/634079/141540714-cf03cbaa-3f07-498d-b395-e12e21e06869.png)

2021-11-24 20:06 UTC, makson96 commented
I haven't found anything suspicious in the code, which could affected that test. I have rerun it and it seems to work.

2021-11-24 20:16 UTC, sharkwouter commented
I'm going to merge this then. Sorry for not checking it out again sooner. I just tested it and it does work quite well.

2021-11-24 20:17 UTC, merged