Fix properties screen for games without a genre
sharkwouter/minigalaxy pull request #420
Opened 2021-11-26 22:51 UTC by mareksapota

Summary: Not all games have the `genre` field populated in gamesdb info.
For example "Jazz Jackrabbit Collection" has an empty list of genres:
https://gamesdb.gog.com/platforms/gog/external_releases/1808582759

Currently trying to open the properties screen for a game without any
listed genres crashes minigalaxy.  This PR changes the API part to
accept an empty list of generes as valid and changes the UI to display
`unknown` if no genres are available.

Test plan: Added a unit test.
```
pytest tests/
```

UI screenshot after changes: ![jazz-genre](https://user-images.githubusercontent.com/479494/143659684-ac5210a5-daaa-44da-84fe-03d8b7542549.png)

2021-11-27 00:31 UTC, makson96 commented
Hi,
This seems to be very important fix. I am not very good at translation. Can we keep changes in translation files in separate pull request so I can check only described fix here?
Best regards,

2021-11-27 00:43 UTC, flagrama commented
Like 99% of the translation files is just automatically updating the comments referring to line numbers in gametile, mainly from my PR being merged. Otherwise it is just adding the new string "unknown" used by this PR and it's kind of a part of it.

2021-11-27 02:04 UTC, mareksapota commented
> Can we keep changes in translation files in separate pull request so I can check only described fix here?

I can split the PR into two if you'd like.  The PR has 2 commits though, first one with the fixes, second one only with the auto generated translation updates.

2021-11-28 19:26 UTC, makson96 requested changes
I have done review.
Thanks for your contribution. This is important fix as it cause application exception. It looks great, but I think that some things can be done simpler. Please check them.

Thanks for new unit test!

I haven't checked translations.
Best regards,

2021-11-28 19:26 UTC, makson96 commented on minigalaxy/api.py
> +            if len(response_json["game"]["genres"]) > 0:
This can be simpler:
```
if response_json["game"]["genres"]:
```

2021-11-28 19:26 UTC, makson96 commented on minigalaxy/ui/properties.py
> +                genre = _("unknown")
I would do such a simple if/else in one line:
```
genre = self.gamesdb_info["genre"]["*"] if "*" in self.gamesdb_info["genre"] else _("unknown")
```

2021-12-17 14:09 UTC, merged

2021-12-17 14:09 UTC, sharkwouter commented
Thanks for the work on this