Fixed localized DLC names
sharkwouter/minigalaxy pull request #482
Opened 2022-04-24 11:08 UTC by TotalCaesar659

GOG has localized names for some games and DLCs (e.g. [Frostpunk: The Rifts](https://www.gog.com/game/frostpunk_the_rifts)), but it provides them based on user's IP. It looks heterogeneous when you want to use English everywhere. This PR fixes it.
Before:
![0](https://user-images.githubusercontent.com/14265316/151784757-fa0dfea1-a1c2-4006-bd38-0bbf7e4765b3.png)
After:
![1](https://user-images.githubusercontent.com/14265316/164973494-ce3dd96f-6e18-461c-940e-d941b79f8e47.png)
I thought about making a switcher for that behavior, but I have a doubt that it'll be in demand. @sharkwouter what do you think?

2022-05-10 20:56 UTC, sharkwouter requested changes

2022-05-10 20:56 UTC, sharkwouter commented on minigalaxy/api.py
> +        request_url = "https://api.gog.com/products/{}?locale=en-US&expand=downloads,expanded_dlcs,description,screenshots," \
I'd say in this case the default is probably preferred over always setting en-US. Is there a way to get a list from the API of supported locales?

2022-05-11 15:50 UTC, TotalCaesar659 commented on minigalaxy/api.py
> +        request_url = "https://api.gog.com/products/{}?locale=en-US&expand=downloads,expanded_dlcs,description,screenshots," \
> Is there a way to get a list from the API of supported locales?

I haven't found easy way for it (perhaps more skilled one can). [API document](https://gogapidocs.readthedocs.io/en/latest/galaxy.html) says that `locale` is just query parameter, not database entry.

> I'd say in this case the default is probably preferred over always setting en-US.

Well, Minigalaxy already processes base game library this way: e.g. it shows [Syberia](https://api.gog.com/products/1207658848?locale=en_US&expand=downloads,expanded_dlcs,description,screenshots,videos,related_products,changelog), not [Сибирь](https://api.gog.com/products/1207658848?locale=ru&expand=downloads,expanded_dlcs,description,screenshots,videos,related_products,changelog) (in Russian). So I just got DLCs to the common denominator.
If we want to use localized names, so it should be for both base games and DLCs. But for me this is the work for future PRs.

2022-09-22 16:53 UTC, TotalCaesar659 commented
@sharkwouter Long time no see, congrats with new release! Could you then merge this?

2022-09-24 09:09 UTC, merged