Action button
sharkwouter/minigalaxy pull request #558
Opened 2023-02-19 15:20 UTC by lmeunier

Not sure of this pull-request as this is an opinionated change.

The menu button, located at the top right corner of the thumbnail, is barely visible for some games. I think it would be better the have this button alongside of the action button (play/download/...).
Should we keep the previous icon ("applications-system-symbolic") or use the default icon for GtkMenuButton?

Also, the first letter of the action button is now capitalized.

Any comments are welcome (I'm not very confident with Gtk).

Before:
![Screenshot from 2023-02-19 16-12-29](https://user-images.githubusercontent.com/1508181/219957260-233b8a51-cadb-4f65-9e62-b377367c27de.png)

After:
![Screenshot from 2023-02-19 16-11-17](https://user-images.githubusercontent.com/1508181/219957282-9083b8d2-cfb3-4580-9a5e-403e65791d0f.png)

2023-02-22 09:51 UTC, sharkwouter commented
Oh nice, that's really cool!

2023-02-22 09:55 UTC, sharkwouter requested changes
I really like this, it looks much better. Thanks for doing this!

I had one comment on the changes, which applies in a couple of places, so I made sure to make all of them. Besides that, could you update CHANGELOG.md as well? Then I'll merge it.

2023-02-22 09:55 UTC, sharkwouter commented on minigalaxy/ui/gametile.py
> +        self.button.set_label(_("Play"))
This change makes it necessary to update all translation files. So we'd either have to leave this change out or update those.

2023-02-22 09:55 UTC, sharkwouter commented on minigalaxy/ui/gametile.py
> +        self.button.set_label(_("Downloading…"))
This change makes it necessary to update all translation files. So we'd either have to leave this change out or update those.

2023-02-22 09:55 UTC, sharkwouter commented on minigalaxy/ui/gametile.py
> +        self.button.set_label(_("In queue…"))
This change makes it necessary to update all translation files. So we'd either have to leave this change out or update those.

2023-02-22 09:55 UTC, sharkwouter commented on minigalaxy/ui/gametile.py
> +        self.button.set_label(_("Updating…"))
This change makes it necessary to update all translation files. So we'd either have to leave this change out or update those.

2023-02-22 19:20 UTC, lmeunier commented
In order to update all translation files, all I have to do is run the script `./scripts/update-translation-files.sh`?

Should I also change the `gametilelist.ui/.py` files? To be honest, I was not aware that the game tiles could be displayed as a list, I just discovered this feature :)

2023-02-23 11:48 UTC, sharkwouter commented
I'd say the best way to update the translations would actually be to go into the `.po` files and replace the translations for these words which are already there with the capitalized ones. Here would be an example: https://github.com/sharkwouter/minigalaxy/blob/766cc7c7071fdd4759c38991114a9ffe5da7646d/data/po/cs_CZ.po#L626

Just running the update script will not yield the result we want, as it will make new entries and the old ones will be ignored.

2023-02-23 17:30 UTC, lmeunier commented
Translations for `msgid "Play"` have been added and some translations for `msgid "Install"` have been fixed.

2023-02-24 12:17 UTC, sharkwouter commented
I've cherry-picked the commits which did not involve the updates to the strings and translation files. Thanks for this change! I don't think I can merge the rest of this right now. Maybe it would be better to have a separate PR for that part.

2023-02-24 16:44 UTC, lmeunier commented
> Maybe it would be better to have a separate PR for that part.

I agree with you. I'll prepare a new PR with only the Capitalization of the first letter.
I think we can close this PR now.

2023-02-24 16:44 UTC, closed without merging

2023-02-24 17:24 UTC, sharkwouter commented
Cool, thanks again for the contribution!