Feature/wine lang install
sharkwouter/minigalaxy pull request #631
Opened 2024-12-22 10:02 UTC by GB609

## Description

This PR is a follow up on #624. Here, I'm doing the rest of the clean up and code rework related to innoextract.
Innoextract will now only be used for language detection during installation and the respective method has been reworked to have a clearer return value and more robust error handling.
I've also completely remove the old extract_by_innoextract install method since it is not used anymore.
Moreover, the new method match_game_lang_to_installer writes the output of innoextract into a log file (game.install_dir/minigalaxy_setup_languages.log).
With that, installing windows games now produces 3 small log files we can use for error reports and analysis:
* game.install._dir/minigalaxy_setup_languages.log - language list from installer (if supported)
* game.install_dir/prefix/drive_c/install.log - Log file of innosetup itself
* game.install_dir/prefix/drive_c/setup.inf - Setup data as per innosetup /SAVEINF

Coupled with everything that now also goes into minigalaxies default logging as error, there should be a lot of information to trace back errors on installations.

## Checklist
 
 - [x] _CHANGELOG.md_ was updated (**format**: - Change made (thanks to github_username))

2025-01-05 12:02 UTC, sharkwouter requested changes
Thanks for this work, I think it is a very nice improvement. I had some minor comments, but generally I'm very happy with this change. Sorry for the late review, I didn't have time to do it during my vacation.

2025-01-06 09:02 UTC, GB609 commented on minigalaxy/installer.py
> +        time.sleep(0.02)
Sure.

2025-01-06 09:06 UTC, GB609 commented on minigalaxy/installer.py
> +    lang_name_regex = re.compile('(\\w+)\\s*:\\s*.*')
I've already added 4 tests in test_installer for this: `test1_get_lang_with_innoextract - test4_get_lang_with_innoextract`.
These tests already do this, albeit not directly by mocking _exe_cmd but the subprocess.popen instead. And the tests `test2_get_lang_with_innoextract - test4_get_lang_with_innoextract` directly call `match_game_lang_to_installer` to see that it actually correctly matches. 
I can change the mock to take popen out of the equation here, no problem. Takes away a bit of the complexity which how the mock is set up.

2025-01-06 09:09 UTC, sharkwouter commented on minigalaxy/installer.py
> +    lang_name_regex = re.compile('(\\w+)\\s*:\\s*.*')
Oh, my bad. I had missed that. I'll resolve this conversation.

2025-01-06 09:17 UTC, merged